version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/project"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "matcharr"
    assignees:
      - "matcharr"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"