# yamllint configuration for Discord bot project
extends: default

rules:
  # Allow longer lines for readability (GitHub Actions can have long URLs)
  line-length:
    max: 120
    level: warning

  # Allow more indentation for complex structures
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Be more lenient with comments (Docker Compose often has commented sections)
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Allow empty values (useful for environment variables)
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Allow truthy values like 'yes', 'no', 'on', 'off' (common in CI/CD)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Allow document start marker to be optional
  document-start: disable

  # Be lenient with comments indentation for Docker Compose
  comments-indentation: disable

ignore: |
  node_modules/
  .venv/
  __pycache__/
  .ruff_cache/
  .pytest_cache/
  .mypy_cache/
